events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  upstream app_pool {
    server app1:8000;
    server app2:8000;
    server app3:8000;
  }

  server {
    listen 80;

    location /ws/ {
      proxy_pass http://app_pool;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 3600s;
    }

    location /healthz {
      proxy_pass http://app_pool;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;
    }
  }
}
